let foods=[{image:"./images/pizaapepperoni.jpg",
            name:"Pizaa with Pepperoni",
            icon  :"🍕",
            price:250},
            {image:"./images/cheesepizza.jpg",
            name:"Pizaa with Cheese",
            icon  :"🍕",
            price:450},
           {image:"./images/Chocolateberrypizaa.jpg",
            name:"Pizaa with Chocolateberry",
            icon  :"🍕",
            price:350},
          {image:"./images/Margheritapizza.jpg",
            name:"Pizaa with Margherita",
            icon  :"🍕",
            price:400},
        {image:"./images/ChacoPizaa.jpg",
            icon  :"🍕",
            name:"Chaco Pizaa",
            price:300},
             {image:"./images/topings.jpg",
            name:"Variety Topings",
            icon  :"🍕",
            price:500}
]